name: Build QMK firmware
# Only run when explicity told to, since this repo is mixed content
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container: qmkfm/qmk_cli
    strategy:
      fail-fast: false
      matrix:
# List of keymap json files to build
        file:
        - preonic_rev3_drop.json
# End of json file list

    steps:

    - name: Checkout QMK
      uses: actions/checkout@v3
      with:
        repository: qmk/qmk_firmware
        submodules: recursive
        path: qmk_firmware

    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        path: ${{ github.actor }}

    # Since this repo isn't a true userspace, do some shuffling
    - name: Move QMK configs to userspace
      run: cp -rp "${{ github.actor }}/qmk" "qmk_firmware/users/${{ github.actor }}"

    - name: Build firmware
      run: qmk compile "users/${{ github.actor }}/${{ matrix.file }}"
      working-directory: qmk_firmware

    # Purely because I can't stand having .json in the middle of the archive name
    - name: Prepare archive name
      id: prepare-archive-name
      run: |
        value=$(basename ${{ matrix.file }} .json)
        echo "::set-output name=value::$value"

    - name: Archive firmware
      uses: actions/upload-artifact@v3
      continue-on-error: true
      with:
        name: ${{ steps.prepare-archive-name.outputs.value }}_${{ github.actor }}
        path: |
          qmk_firmware/*.hex
          qmk_firmware/*.bin
          qmk_firmware/*.uf2